### ISSUE TITLE
Can't run serve on nuxt plugin

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [edbzn/nx-nuxt#32]
Hi, I'm pretty new to nx and I'm having a weird error. I really don't know how to give more info about this error, but I can't call serve on my current project. This is the first time I'm using nx-nuxt

![image](https://user-images.githubusercontent.com/20716785/97066028-1d862c00-1588-11eb-9716-ed5a9d9a2c90.png)

**Comment by edbzn** [comment]
Hi @AllanPinheiroDeLima thanks for reporting this. Sorry for the delay I didn't see the notification. I just fixed the problem, you can just reinstall the package and rerun the command :

```bash
yarn add @edbzn/nuxt -D # or npm install @edbzn/nuxt -D
```
